language: php

php:
  - 5.6
  - 7
  - hhvm

sudo: false

install:
  - composer selfupdate
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer global require --update-no-dev schnittstabil/sugared-php_codesniffer:dev-master@dev; fi
  - composer install
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer global require --update-no-dev codeclimate/php-test-reporter phpmd/phpmd satooshi/php-coveralls fabpot/php-cs-fixer; fi
  - export PATH=$PATH:`composer global config bin-dir --absolute`

script:
  - composer travis
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer lint; fi

after_success:
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then test-reporter; fi
  - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then coveralls -v; fi

addons:
  code_climate:
    repo_token: 0f8401dd474e697bec3f1f5ef8925ed972078ec09b6e7adc0b8a7ecdeb3220dc
